version: '3.9'
services:
  dev:
    container_name: page_starter_dev
    build:
      context: ./docker/dev
    platform: linux/amd64
    volumes:
      - './:/page'
    working_dir: '/page'
    command: [ '/bin/sh', '-c', 'tail -f /dev/null' ]
    restart: always
    ports:
      - '4000:4000'
  node:
    container_name: page_starter_node
    build:
      context: ./docker/node
    platform: linux/amd64
    volumes:
      - './:/page'
    working_dir: '/page'
    command: [ '/bin/sh', '-c', 'tail -f /dev/null' ]
    restart: always